module.exports = Object.freeze({
  PLAYER_RADIUS: 20,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 400,
  PLAYER_FIRE_COOLDOWN: 0.25,

  BULLET_RADIUS: 3,
  BULLET_SPEED: 800,
  BULLET_DAMAGE: 10,
  BULLET_SPREAD: Math.PI/180,

  UPGRADE_RADIUS: 9,
  UPGRADE_SPIN_RATE: 0.05,

  SCORE_UPGRADE_ACQUIRED: 10,
  SCORE_BULLET_HIT: 20,
  SCORE_PER_SECOND: 1,

  MAX_UPGRADES: 20,

  MAP_SIZE: 3000,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    GAME_OVER: 'dead',
    CHAT: 'chat',
  },

  // in seconds
  CHAT_TTL: 4,
});
